version: '3.7'

x-ruby: &ruby-base
  build:
    context: ./
    args:
      - RAILSDOCK_RUBY_VERSION=${RAILSDOCK_RUBY_VERSION}
      - RAILSDOCK_NODE_VERSION=${RAILSDOCK_NODE_VERSION}
      - RUBY_UID=1000
      - RUBY_GID=1000
  volumes:
    - .:/app
    - gems:/gems
    - node_modules:/app/node_modules
    - packs:/app/public/packs
    - rails_cache:/app/tmp/cache
  tmpfs:
    - /tmp
  tty: true
  stdin_open: true
  # depends_on:
  #   - postgres
  #   - redis

volumes:
  redis:
  postgres:
  gems:
  node_modules:

services:

  rails:
    <<: *ruby-base
    build:
      context: .
      args:
        - RAILSDOCK_BUNDLE_JOBS=${BUNDLE_JOBS}
        - RAILSDOCK_BUNDLE_RETRY=${BUNDLE_RETRY}
    environment:
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
    volumes:
      - .:${APP_CODE_PATH_CONTAINER}
      - gems:/gems
      - node_modules:${APP_CODE_PATH_CONTAINER}/node_modules
    ports:
      - "${RAILS_SERVER_HOST_PORT}:3000"
    command: "rails server -p 3000 -b 0.0.0.0"
    tty: true
    stdin_open: true

  # postgres:
  #   image: postgres:12.1
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres:/var/lib/postgresql/data

  # redis:
  #   image: redis:5.0.7
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis:/data
